services:
  backend:
    container_name: vortex-backend
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - vortex-backend-data:/app/data

  frontend:
    container_name: vortex-frontend
    build: ./frontend
    ports:
      - "8080:80"

volumes:
  vortex-backend-data:
